// This file is automatically generated.
// Tip: To ensure your application is configured correctly, create a new
// file named `.env.local` in the root of your project and paste the
// following content into it. You can then retrieve your credentials from
// the Firebase console.
/*
NEXT_PUBLIC_FIREBASE_API_KEY="AIza..."
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="my-project.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID="my-project"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="my-project.appspot.com"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID="12345"
NEXT_PUBLIC_FIREBASE_APP_ID="1:12345:web:abcd"
*/

export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
};

export const isFirebaseEnabled =
  firebaseConfig.apiKey !== undefined && firebaseConfig.projectId !== undefined;
